### ISSUE TITLE
Support for Moodle v. 3.8

### ISSUE THREAD

**Issue by kloevschall** [lucisgit/moodle-mod_leganto#1]
Hi,

Are there any plans of supporting Moodle version 3.8 by this plugin?

Best regards,
Kasper Løvschall

**Comment by tonyjbutler** [comment]
Hi Kasper,
Yes, we're planning to upgrade to Moodle 3.8 soon so we will be testing and updating all of our plugins with 3.8 in the next few weeks. Have you tried it yet? Often they just work fine anyway.
Thanks,
Tony

**Comment by kloevschall** [comment]
Thanks Tony,

Sounds good! We are just in the beginning of working with the integration between Moodle and Leganto so we haven't tried anything yet.

Best,
Kasper

**Comment by tonyjbutler** [comment]
Tested in Moodle 3.8 and 3.9 (forgot to close issue earlier).
